# Conexion a RabbitMQ

#sale
# crear y actualizar
comercial.sale.save.exchange-name=ucopet.comercial.sale.save.ex
comercial.sale.save.queue-name=ucopet.comercial.sale.save.qu
comercial.sale.save.routing-key-name=ucopet.comercial.sale.save.rk

# desactivar
comercial.sale.deactivate.exchange-name=ucopet.comercial.sale.deactivate.ex
comercial.sale.deactivate.queue-name=ucopet.comercial.sale.deactivate.qu
comercial.sale.deactivate.routing-key-name=ucopet.comercial.sale.deactivate.rk


#provider
# crear y actualizar
comercial.provider.save.exchange-name=ucopet.comercial.provider.save.ex
comercial.provider.save.queue-name=ucopet.comercial.provider.save.qu
comercial.provider.save.routing-key-name=ucopet.comercial.provider.save.rk
# desactivar
comercial.provider.deactivate.exchange-name=ucopet.comercial.provider.deactivate.ex
comercial.provider.deactivate.queue-name=ucopet.comercial.provider.deactivate.qu
comercial.provider.deactivate.routing-key-name=ucopet.comercial.provider.deactivate.rk

#purchases
# crear y actualizar
comercial.purchases.save.exchange-name=ucopet.comercial.purchases.save.ex
comercial.purchases.save.queue-name=ucopet.comercial.purchases.save.qu
comercial.purchases.save.routing-key-name=ucopet.comercial.purchases.save.rk
# desactivar
comercial.purchases.deactivate.exchange-name=ucopet.comercial.purchases.deactivate.ex
comercial.purchases.deactivate.queue-name=ucopet.comercial.purchases.deactivate.qu
comercial.purchases.deactivate.routing-key-name=ucopet.comercial.purchases.deactivate.rk

#healthPlan
# crear y actualizar
comercial.healthPlan.save.exchange-name=ucopet.comercial.healthPlan.save.ex
comercial.healthPlan.save.queue-name=ucopet.comercial.healthPlan.save.qu
comercial.healthPlan.save.routing-key-name=ucopet.comercial.healthPlan.save.rk
# desactivar
comercial.healthPlan.deactivate.exchange-name=ucopet.comercial.healthPlan.deactivate.ex
comercial.healthPlan.deactivate.queue-name=ucopet.comercial.healthPlan.deactivate.qu
comercial.healthPlan.deactivate.routing-key-name=ucopet.comercial.healthPlan.deactivate.rk
