# Conexion a RabbitMQ

#sale
# crear y actualizar
commercial.sale.save.exchange-name=ucopet.commercial.sale.save.ex
commercial.sale.save.queue-name=ucopet.commercial.sale.save.qu
commercial.sale.save.routing-key-name=ucopet.commercial.sale.save.rk

# desactivar
commercial.sale.deactivate.exchange-name=ucopet.commercial.sale.deactivate.ex
commercial.sale.deactivate.queue-name=ucopet.commercial.sale.deactivate.qu
commercial.sale.deactivate.routing-key-name=ucopet.commercial.sale.deactivate.rk


#provider
# crear y actualizar
commercial.provider.save.exchange-name=ucopet.commercial.provider.save.ex
commercial.provider.save.queue-name=ucopet.commercial.provider.save.qu
commercial.provider.save.routing-key-name=ucopet.commercial.provider.save.rk
# desactivar
commercial.provider.deactivate.exchange-name=ucopet.commercial.provider.deactivate.ex
commercial.provider.deactivate.queue-name=ucopet.commercial.provider.deactivate.qu
commercial.provider.deactivate.routing-key-name=ucopet.commercial.provider.deactivate.rk

#purchases
# crear y actualizar
commercial.purchases.save.exchange-name=ucopet.commercial.purchases.save.ex
commercial.purchases.save.queue-name=ucopet.commercial.purchases.save.qu
commercial.purchases.save.routing-key-name=ucopet.commercial.purchases.save.rk
# desactivar
commercial.purchases.deactivate.exchange-name=ucopet.commercial.purchases.deactivate.ex
commercial.purchases.deactivate.queue-name=ucopet.commercial.purchases.deactivate.qu
commercial.purchases.deactivate.routing-key-name=ucopet.commercial.purchases.deactivate.rk

#healthPlan
# crear y actualizar
commercial.healthPlan.save.exchange-name=ucopet.commercial.healthPlan.save.ex
commercial.healthPlan.save.queue-name=ucopet.commercial.healthPlan.save.qu
commercial.healthPlan.save.routing-key-name=ucopet.commercial.healthPlan.save.rk
# desactivar
commercial.healthPlan.deactivate.exchange-name=ucopet.commercial.healthPlan.deactivate.ex
commercial.healthPlan.deactivate.queue-name=ucopet.commercial.healthPlan.deactivate.qu
commercial.healthPlan.deactivate.routing-key-name=ucopet.commercial.healthPlan.deactivate.rk
