
# Conexion a RabbitMQ

#petcare
# crear y actualizar
health.petcare.save.exchange-name=ucopet.health.petcare.save.ex
health.petcare.save.queue-name=ucopet.health.petcare.save.qu
health.petcare.save.routing-key-name=ucopet.health.petcare.save.rk
# desactivar
health.petcare.deactivate.exchange-name=ucopet.health.petcare.deactivate.ex
health.petcare.deactivate.queue-name=ucopet.health.petcare.deactivate.qu
health.petcare.deactivate.routing-key-name=ucopet.health.petcare.deactivate.rk

#order
# crear y actualizar
health.order.save.exchange-name=ucopet.health.order.save.ex
health.order.save.queue-name=ucopet.health.order.save.qu
health.order.save.routing-key-name=ucopet.health.order.save.rk
# desactivar
health.order.deactivate.exchange-name=ucopet.health.order.deactivate.ex
health.order.deactivate.queue-name=ucopet.health.order.deactivate.qu
health.order.deactivate.routing-key-name=ucopet.health.order.deactivate.rk

#appointment
# crear y actualizar
health.appointment.save.exchange-name=ucopet.health.appointment.save.ex
health.appointment.save.queue-name=ucopet.health.appointment.save.qu
health.appointment.save.routing-key-name=ucopet.health.appointment.save.rk
# desactivar
health.appointment.deactivate.exchange-name=ucopet.health.appointment.deactivate.ex
health.appointment.deactivate.queue-name=ucopet.health.appointment.deactivate.qu
health.appointment.deactivate.routing-key-name=ucopet.health.appointment.deactivate.rk

#specialty
# crear y actualizar
health.specialty.save.exchange-name=ucopet.health.specialty.save.ex
health.specialty.save.queue-name=ucopet.health.specialty.save.qu
health.specialty.save.routing-key-name=ucopet.health.specialty.save.rk
# desactivar
health.specialty.deactivate.exchange-name=ucopet.health.specialty.deactivate.ex
health.specialty.deactivate.queue-name=ucopet.health.specialty.deactivate.qu
health.specialty.deactivate.routing-key-name=ucopet.health.specialty.deactivate.rk

#procedure
# crear y actualizar
health.procedure.save.exchange-name=ucopet.health.procedure.save.ex
health.procedure.save.queue-name=ucopet.health.procedure.save.qu
health.procedure.save.routing-key-name=ucopet.health.procedure.save.rk
# desactivar
health.procedure.deactivate.exchange-name=ucopet.health.procedure.deactivate.ex
health.procedure.deactivate.queue-name=ucopet.health.procedure.deactivate.qu
health.procedure.deactivate.routing-key-name=ucopet.health.procedure.deactivate.rk

#space
# crear y actualizar
health.space.save.exchange-name=ucopet.health.space.save.ex
health.space.save.queue-name=ucopet.health.space.save.qu
health.space.save.routing-key-name=ucopet.health.space.save.rk
# desactivar
health.space.deactivate.exchange-name=ucopet.health.space.deactivate.ex
health.space.deactivate.queue-name=ucopet.health.space.deactivate.qu
health.space.deactivate.routing-key-name=ucopet.health.space.deactivate.rk
