spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

ucopet.rabbitmq.user.exchange=ucopet.user.exchange
ucopet.rabbitmq.user.queue=ucopet.user.queue
ucopet.rabbitmq.user.routing-key=ucopet.user.routing-key